import "./Heart.css"
export function Heart() {
    return (
        <div className="container">
            <div className="heart">Heart</div>
            <div className="spark spark1"></div>
            <div className="spark spark2"></div>
            <div className="spark spark3"></div>
            <div className="spark spark4"></div>
            <div className="spark spark5"></div>
            <div className="spark spark6"></div>
            <div className="spark spark7"></div>
            <div className="spark spark8"></div>
            <div className="spark spark9"></div>
            <div className="spark spark10"></div>
            <div className="spark spark11"></div>
            <div className="spark spark12"></div>
            <div className="spark spark13"></div>
            <div className="spark spark14"></div>
            <div className="spark spark15"></div>
            <div className="spark spark16"></div>
            <div className="spark spark17"></div>
            <div className="spark spark18"></div>
            <div className="spark spark19"></div>
            <div className="spark spark20"></div>
            <div className="spark spark21"></div>
            <div className="spark spark22"></div>
            <div className="spark spark23"></div>
            <div className="spark spark24"></div>
            <div className="spark spark25"></div>
            <div className="spark spark26"></div>
            <div className="spark spark27"></div>
            <div className="spark spark28"></div>
            <div className="spark spark29"></div>
            <div className="spark spark30"></div>
            <div className="spark spark31"></div>
            <div className="spark spark32"></div>
            <div className="spark spark33"></div>
            <div className="spark spark34"></div>
            <div className="spark spark35"></div>
            <div className="miniheart h1"></div>
            <div className="miniheart h2"></div>
            <div className="miniheart h3"></div>
            <div className="miniheart h4"></div>
            <div className="miniheart h5"></div>
            <div className="miniheart h6"></div>
            <div className="miniheart h7"></div>
            <div className="miniheart h8"></div>
            <div className="miniheart h9"></div>
            <div className="miniheart h10"></div>
            <div className="miniheart h11"></div>
            <div className="miniheart h12"></div>
            <div className="miniheart h13"></div>
            <div className="miniheart h14"></div>
            <div className="miniheart h15"></div>
            <div className="miniheart h16"></div>
            <div className="miniheart h17"></div>
            <div className="miniheart h18"></div>
            <div className="miniheart h19"></div>
            <div className="miniheart h20"></div>
            <div className="miniheart h21"></div>
            <div className="miniheart h22"></div>
            <div className="miniheart h23"></div>
            <div className="miniheart h24"></div>
            <div className="miniheart h25"></div>
            <div className="miniheart h26"></div>
            <div className="miniheart h27"></div>
            <div className="miniheart h28"></div>
            <div className="miniheart h29"></div>
            <div className="miniheart h30"></div>
            <div className="miniheart h31"></div>
            <div className="miniheart h32"></div>
            <div className="miniheart h33"></div>
            <div className="miniheart h34"></div>
            <div className="miniheart h35"></div>
            <div className="miniheart h36"></div>
            <div className="miniheart h37"></div>
            <div className="miniheart h38"></div>
        </div>
    )
}